OKXGENERALEXCEPTIONS = {
    #GENERAL CLASS
    'response_code': '1', 'http_code': '200', 'msg': 'Operation failed.',
    'response_code': '2', 'http_code': '200', 'msg': 'Bulk operation partially succeeded.',
    'response_code': '50000', 'http_code': '400', 'msg': 'Body for POST request cannot be empty.',
    'response_code': '50001', 'http_code': '503', 'msg': 'Service temporarily unavailable. Try again later',
    'response_code': '50002', 'http_code': '400', 'msg': 'JSON syntax error',
    'response_code': '50004', 'http_code': '400', 'msg': 'API endpoint request timeout (does not mean that the request was successful or failed, please check the request result).',
    'response_code': '50005', 'http_code': '410', 'msg': 'API is offline or unavailable.',
    'response_code': '50006', 'http_code': '400', 'msg': 'Invalid Content-Type. Please use "application/JSON".',
    'response_code': '50007', 'http_code': '200', 'msg': 'Account blocked.',
    'response_code': '50008', 'http_code': '200', 'msg': 'User does not exist.',
    'response_code': '50009', 'http_code': '200', 'msg': 'Account is suspended due to ongoing liquidation.',
    'response_code': '50010', 'http_code': '200', 'msg': 'User ID cannot be empty.',
    'response_code': '50011', 'http_code': '200', 'msg': 'Rate limit reached. Please refer to API documentation and throttle requests accordingly.',
    'response_code': '50011', 'http_code': '429', 'msg': 'Requests too frequent',
    'response_code': '50012',  'http_code': '200', 'msg': 'Account status invalid. Check account status',
    'response_code': '50013',  'http_code': '429', 'msg': 'Systems are busy. Please try again later.',
    'response_code': '50014',  'http_code': '400', 'msg': 'Parameter {param0} cannot be empty.',
    'response_code': '50015',  'http_code': '400', 'msg': 'Either parameter {param0} or {param1} is required.',
    'response_code': '50016',  'http_code': '400', 'msg': 'Parameter {param0} and {param1} is an invalid pair.',
    'response_code': '50017',  'http_code': '200', 'msg': 'Position frozen and related operations restricted due to auto-deleveraging (ADL). Try again later',
    'response_code': '50018',  'http_code': '200', 'msg': '{param0} frozen and related operations restricted due to auto-deleveraging (ADL). Try again later',
    'response_code': '50019',  'http_code': '200', 'msg': 'Account frozen and related operations restricted due to auto-deleveraging (ADL). Try again later',
    'response_code': '50020',  'http_code': '200', 'msg': 'Position frozen and related operations are restricted due to liquidation. Try again later',
    'response_code': '50021',  'http_code': '200', 'msg': '{param0} frozen and related operations are restricted due to liquidation. Try again later',
    'response_code': '50022',  'http_code': '200', 'msg': 'Account frozen and related operations are restricted due to liquidation. Try again later',
    'response_code': '50023',  'http_code': '200', 'msg': 'Funding fees frozen and related operations are restricted. Try again later',
    'response_code': '50024',  'http_code': '200', 'msg': 'Either parameter {param0} or {param1} should be submitted.',
    'response_code': '50025',  'http_code': '200', 'msg': 'Parameter {param0} count exceeds the limit {param1}.',
    'response_code': '50026',  'http_code': '500', 'msg': 'System error. Try again later',
    'response_code': '50027',  'http_code': '200', 'msg': 'This account is restricted from trading. Please contact customer support for assistance.',
    'response_code': '50028',  'http_code': '200', 'msg': 'Unable to take the order, please reach out to support center for details.',
    'response_code': '50029',  'http_code': '200', 'msg': 'Your account has triggered OKX risk control and is temporarily restricted from conducting transactions. Please check your email registered with OKX for contact from our customer support team.',
    'response_code': '50030',  'http_code': '200', 'msg': 'You don\'t have permission to use this API endpoint',
    'response_code': '50032',  'http_code': '200', 'msg': 'Your account has been set to prohibit transactions in this currency. Please confirm and try again',
    'response_code': '50033',  'http_code': '200', 'msg': 'Instrument blocked. Please verify trading this instrument is allowed under account settings and try again.',
    'response_code': '50035',  'http_code': '403', 'msg': 'This endpoint requires that APIKey must be bound to IP',
    'response_code': '50036',  'http_code': '200', 'msg': 'The expTime can\'t be earlier than the current system time. Please adjust the expTime and try again.',
    'response_code': '50037',  'http_code': '200', 'msg': 'Order expired.',
    'response_code': '50038',  'http_code': '200', 'msg': 'This feature is unavailable in demo trading',
    'response_code': '50039',  'http_code': '200', 'msg': 'Parameter "before" isn\'t supported for timestamp pagination',
    'response_code': '50040',  'http_code': '200', 'msg': 'Too frequent operations, please try again later',
    'response_code': '50041',  'http_code': '200', 'msg': 'Your user ID hasn\'t been allowlisted. Please contact customer service for assistance.',
    'response_code': '50044',  'http_code': '200', 'msg': 'Must select one broker type',
    'response_code': '50047',  'http_code': '200', 'msg': '{param0} has already settled. To check the relevant candlestick data, please use {param1}',
    'response_code': '50048',  'http_code': '200', 'msg': 'Switching risk unit may lead position risk increases and be forced liquidated. Please adjust position size, make sure margin is in a safe status.',
    'response_code': '50049',  'http_code': '200', 'msg': 'No information on the position tier. The current instrument doesn\'t support margin trading.',
    'response_code': '50050',  'http_code': '200', 'msg': 'You\'ve already activated options trading. Please don\'t activate it again.',
    'response_code': '50051',  'http_code': '200', 'msg': 'Due to compliance restrictions in your country or region, you cannot use this feature.',
    'response_code': '50052',  'http_code': '200', 'msg': 'Due to local laws and regulations, you cannot trade with your chosen crypto.',
    'response_code': '50053',  'http_code': '200', 'msg': 'This feature is only available in demo trading.',
    'response_code': '50055',  'http_code': '200', 'msg': 'Reset unsuccessful. Assets can only be reset up to 5 times per day.',
    'response_code': '50056',  'http_code': '200', 'msg': 'You have pending orders or open positions with this currency. Please reset after canceling all the pending orders/closing all the open positions.',
    'response_code': '50057',  'http_code': '200', 'msg': 'Reset unsuccessful. Try again later.',
    'response_code': '50058',  'http_code': '200', 'msg': 'This crypto is not supported in an asset reset.',
    'response_code': '50059',  'http_code': '200', 'msg': 'Before you continue, you\'ll need to complete additional steps as required by your local regulators. Please visit the website or app for more details.',
    'response_code': '50060',  'http_code': '200', 'msg': 'For security and compliance purposes, please complete the identity verification process to continue using our services.',
    'response_code': '50061',  'http_code': '200', 'msg': 'You\'ve reached the maximum order rate limit for this account.',
    'response_code': '50063',  'http_code': '200', 'msg': 'You can\'t activate the credits as they might have expired or are already activated.',
    'response_code': '50064',  'http_code': '200', 'msg': 'The borrowing system is unavailable. Try again later.',
}
